### ISSUE TITLE
Can't install game. Anyone know what might be causing this?(Error code attached as comment)

### ISSUE THREAD

**Issue by EndNefric** [OpenViva/OpenVivaLauncher#8]
Throw Location: Location not provided
============================
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The response ended prematurely, with at least 680088379 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at OpenVivaLauncher.GithubService.GetAssetsAsync(String assetUrl, String path)
   at OpenVivaLauncher.GithubService.DownloadVersionAsync(String versionKey, String path)
   at OpenVivaLauncher.GameService.InstallGameVersion(String version, SemVersion semVer)
   at OpenVivaLauncher.MainWindow.LaunchButton_OnClick(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EndNefric** [comment]
To add on to the information about this issue, the installation goes smoothly until about the 20% mark and then the installer crashes.
